Add -lpthread to link command to fix build with GCC 5.1
Build with GCC 5.1 failed with error:
[  253s] /usr/lib/gcc/i586-tizen-linux/5.1/../../../../i586-tizen-linux/bin/ld: CMakeFiles/askuser.dir/main/CynaraTalker.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.1'
[  253s] /usr/lib/libpthread.so.0: error adding symbols: DSO missing from command line
[  253s] collect2: error: ld returned 1 exit status

Adding -lpthread to link command fixes the issue

Change-Id: Id1514630890839f94e7eaa6406ef90610bd50f74
Signed-off-by: Yury Usishchev <y.usishchev@samsung.com>